# Generated by Django 3.2.10 on 2022-04-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('deg', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('passw', models.CharField(max_length=20)),
                ('mob', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
