# Generated by Django 3.2.10 on 2022-04-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20220406_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
