# Generated by Django 3.2.10 on 2022-04-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_alter_employees_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('Fathername', models.CharField(max_length=20)),
                ('std', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('PhyMarks', models.IntegerField()),
                ('CheMarks', models.IntegerField()),
                ('MathMarks', models.IntegerField()),
                ('mob', models.IntegerField()),
                ('Add', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.FloatField(),
        ),
    ]
