# Generated by Django 3.2.10 on 2022-04-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20220409_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('Fathername', models.CharField(max_length=20)),
                ('std', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('PhyMarks', models.IntegerField()),
                ('CheMarks', models.IntegerField()),
                ('MathMarks', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mob', models.IntegerField()),
                ('Add', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
